#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/../../"

CONFIG_PATH="${PWD}/.devcontainer/config"

# Create config dir if not present
if [[ ! -d "$CONFIG_PATH" ]]; then
    mkdir -p "$CONFIG_PATH"
    hass --config "$CONFIG_PATH" --script ensure_config
fi

# Set the path to custom_components
## This let's us have the structure we want <root>/custom_components/ferroamp
## while at the same time have Home Assistant configuration inside <root>/.devcontainer/config
## without resulting to symlinks.
export PYTHONPATH="${PYTHONPATH}:${PWD}/custom_components"

if [[ ! -z "$DEBUG" ]]; then
    echo "Debug mode"
    # Start Home Assistant in debug mode see: https://github.com/home-assistant/core/issues/110623
    python3 -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 -m homeassistant --config "$CONFIG_PATH"
else
    # Start Home Assistant
    hass --config "$CONFIG_PATH"
fi
