"""Constants for Ferroamp"""

CONF_INTERVAL = "interval"
CONF_PRECISION_BATTERY = "precision_battery"
CONF_PRECISION_CURRENT = "precision_current"
CONF_PRECISION_ENERGY = "precision_energy"
CONF_PRECISION_TEMPERATURE = "precision_temperature"
CONF_PRECISION_VOLTAGE = "precision_voltage"
DATA_DEVICES = "devices"
DATA_LISTENERS = "listeners"
DATA_PREFIXES = "prefixes"
DOMAIN = "ferroamp"
MANUFACTURER = "Ferroamp"
